name: California Tech template record creation

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Publication date (format 2026-03-19)'
        required: true
      volume:
        description: 'Volume'
        required: true
      issue:
        description: 'Issue'
        required: true

jobs:
  template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Python Deps
        shell: bash
        run: pip install -r requirements.txt --break-system-packages
      - name: Create template
        shell: bash
        env:
            RDMTOK: ${{ secrets.RDMTOK }}
        id: template
        run: python template.py california_tech -date ${{ github.event.inputs.date }} -issue ${{ github.event.inputs.issue }} -volume ${{ github.event.inputs.volume }} -actor ${{github.actor}
