name: Harvest from DOI

on:
  workflow_dispatch:
    inputs:
      doi:
        description: 'DOI or multiple DOIs (separated by a space) to harvest from'
        required: true

jobs:
  prepare-dois:
    name: Prepare Matrix Output of DOIs
    runs-on: ubuntu-latest
    outputs: 
      dois: ${{ steps.step1.outputs.matrix }}
    env:
      DOI: ${{ github.event.inputs.doi }}
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Process DOIs
        shell: bash
        run: python split_doi.py
      - name: Create Matrix Variable
        id: step1
        run: echo "matrix=$DOI" >> $GITHUB_OUTPUT
  Harvest:
    runs-on: ubuntu-latest
    needs: [prepare-dois]
    strategy:
      fail-fast: false
      matrix:
        doi: ${{ fromJSON(needs.prepare-dois.outputs.dois) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python Deps
        shell: bash
        run: pip install -r requirements.txt
      - name: Make downloads folder
        shell: bash
        run: mkdir $HOME/Downloads
      - name: Install irdmtools
        shell: bash
        run: curl https://caltechlibrary.github.io/irdmtools/installer.sh | sh
      - name: Path
        shell: bash
        run: cp $HOME/bin/doi2rdm $HOME/.local/bin/.
      - name: Harvest DOIs
        shell: bash
        env:
            RDMTOK: ${{ secrets.RDMTOK }}
        run: python harvest.py doi -doi "${{matrix.doi}}" -actor ${{github.actor}} 
      - name: Commit File
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update harvested_dois.txt'
          add: "['harvested_dois.txt']"
