name: Harvest

on:
  push:
    tags:
      - v*    
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Harvest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python Deps
        shell: bash
        run: pip install -r requirements.txt
      - name: Make downloads folder
        shell: bash
        run: mkdir $HOME/Downloads
      - name: Install irdmtools
        shell: bash
        run: curl https://caltechlibrary.github.io/irdmtools/installer.sh | sh
      - name: Path
        shell: bash
        run: cp $HOME/bin/doi2rdm $HOME/.local/bin/.
      - name: Path2
        shell: bash
        run: echo $PATH
      - name: Path3
        shell: bash
        run: doi2rdm --version
      - name: Harvest DOIs
        shell: bash
        env:
            RDMTOK: ${{ secrets.RDMTOK }}
        run: python harvest.py 
      - name: Commit CFF
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update run date'
          add: "['last_run.txt', 'harvested_dois.txt']"
